name: Tests

on: [push, pull_request]

jobs:
  run_test_site:
    name: py${{ matrix.PYTHON_VERSION }}${{ matrix.LABEL }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      MPLBACKEND: agg
      PIP_ARGS: --upgrade --use-feature=2020-resolver -e
      PYTEST_ARGS: --pyargs hyperspy_gui_traitsui
      PYTEST_ARGS_COVERAGE: 
    strategy:
      fail-fast: false
      matrix:
        PYTHON_VERSION: [3.6, 3.7]
        PIP_SELECTOR: ['[tests]']
        include:
          - PYTHON_VERSION: 3.8
            PIP_SELECTOR: '[tests, coverage]'
            PYTEST_ARGS_COVERAGE: --cov=. --cov-report=xml
            LABEL: /coverage
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: ${{ matrix.PYTHON_VERSION }}

      - name: Display version
        run: |
          python --version
          pip --version

      - name: Install
        shell: bash
        run: |
          pip install ${{ env.PIP_ARGS }} .'${{ matrix.PIP_SELECTOR }}'
          pip install https://github.com/hyperspy/hyperspy/archive/RELEASE_next_minor.zip

      - name: Run test suite
        run: |
          pytest ${{ env.PYTEST_ARGS }} ${{ matrix.PYTEST_ARGS_COVERAGE }}

      - name: Upload coverage to Codecov
        if: ${{ always() }} && ${{ matrix.PYTEST_ARGS_COVERAGE }} 
        uses: codecov/codecov-action@v1
